### ISSUE TITLE
Which resolvers?

### ISSUE THREAD

**Issue by willmruzek** [alumbra/alumbra#14]
I'm still in the process of writing my first GraphQL server with alumbra and claro. I'm struggling to put the pieces together. Eventually, I'd like to write a guide, blog post, or realistic example to help others out.

Until then, I need some guidance.

I'm trying to set up an API that has the following schema:
```
type User {
    id: String!,
    firstName: String!,
    email: String!
}

type QueryRoot {
  me: User!,
  user(id: String!): User!,
  allUsers: [User]
}

schema { query: QueryRoot }
```

I currently implement resolvers like the following:
```
(defrecord User [id]
  data/Resolvable
  (resolve! [_ _]
    (d/future
     (when-let [user (db/get-user {:id id})]
      {:id id
       :first-name  (str "Person #" id)
       :email "email@email.com"})))

  data/Resolvable
  data/BatchedResolvable
  (resolve-batch! [_ env a-batch-of-users]
    (d/future
      (db/get-users {:ids (map :id a-batch-of-users)}))))

(defrecord Users []
  data/Resolvable
  (resolve! [_ _]
    (->> (db/get-user-ids)
         (map :id)
         (map ->User))))

(def QueryRoot
  {:user (->User nil)
   :all-users (->Users)})
```
 
There are two issues so far:
1. To retrieve all users, we have to make two DB queries.
2. I'm confused on whether I need to implement both `resovle!` and `resolve-batch!` under the same record. Also, do I even need `Users`? I'm confused about how they all interact (or don't).

Appreciate any help or feedback you can give, thanks.

**Comment by xsc** [comment]
Thanks for reaching out again! This is a nice indicator for me where the documentation is lacking so don't hesitate to add more questions as they pop up. :)

> To retrieve all users, we have to make two DB queries.

That is true. I don't see this as an issue, though, due to the benefits arising from this kind of split:

- `User` records are guaranteed to have the same shape wherever they pop up so you only have to touch one piece of code/SQL if you want to change it (as opposed to e.g. multiple list queries).
- You are free to move either functionality to a different datastore, e.g. do searching/listing in something like ElasticSearch and the lookups by ID in a relational DB.
- Especially in a GraphQL context it's probable that this cost will amortise. For example, if I request something like `{ me { id }, allUsers { id } }` I'll need two queries no matter whether `Users` returns full results or `User` records.

All that said, no one stops you from optimising `Users` to return full results – I'd just hold off on doing that unless you're actually experiencing degrading performance.

> I'm confused on whether I need to implement both resovle! and resolve-batch! under the same record.

For claro ≥ 0.2.7 it's enough to just implement `BatchedResolvable` – before that one had to add `Resolvable` as a marker protocol (i.e. without a concrete implementation).

> Also, do I even need Users?

You'll need some way of resolving the `allUsers` field, so yes, I think you need something like the `Users` record. (As mentioned above, you can still choose to let it return full results, but that would remove `User`, not `Users`.)

**Comment by willmruzek** [comment]
Alright, that all makes sense. I have something working, thank you!

I'm onto the mutation part of the API and I think I have functioning update scheme. But I'm curious how to create an entity. Here is my current set up:

```
(defrecord Video [id]
  data/BatchedResolvable
  (resolve-batch! [_ env a-batch-of-videos]
    (d/future
      (db/get-videos {:ids (map :id a-batch-of-videos)}))))

(defrecord MutatedVideo [id title]
  data/Mutation
  data/Resolvable
  (resolve! [_ _]
    (db/update-video! {:id id :title title})
    (db/get-video {:id id})))

(def MutationRoot
  {:update-video (->MutatedVideo nil nil)})

(def handler
  (alumbra/handler
    {:schema schema
     :query  QueryRoot
     :mutation MutationRoot
     :context (fn [request]
                (:identity request))}))
```

**Comment by xsc** [comment]
You'll need the ID of the inserted row to reference the created object. Most DB libraries will offer one way or another to retrieve it after insertion (e.g. `<!` queries in YeSQL/HugSQL or [`db-do-prepared-return-keys`](http://clojure.github.io/java.jdbc/#clojure.java.jdbc/db-do-prepared-return-keys) in plain `clojure.java.jdbc`). Afterwards, you can return a `Video` object that will resolve to the inserted entity:

```clojure
(defrecord CreateVideo [data]
  data/Mutation
  data/Resolvable
  (resolve! [_ env]
    (d/future
      (let [{:keys [user-id]} env
            created-id        (db/create-video! user-id data)]
        (->Video created-id)))))
```

A matching GraphQL schema might look something like this:

```graphql
input VideoInput {
  title: String!
  year: Int!
}

type MutationRoot {
  createVideo(data: VideoInput!): Video
  ...
}

schema {
  mutation: MutationRoot
  ...
}
```

**Comment by willmruzek** [comment]
I hadn't thought about using an `input`. This all makes sense. Thanks again!
